/* tslint:disable */
/* eslint-disable */
/**
 * 냥팔자 API 명세
 * 냥파자는 상팔자 어플리케이션을 위한 API 명세서입니다. - 모든 API의 Path는 **\'/api\'로 시작**합니다. - 모든 API의 응답은 **공통 응답 형식**을 가집니다. data에 실제 응답 데이터가 들어갑니다.     ```json     {       \"requestId\": \"서버생성 요청ID\",       \"requestTime\": \"요청시간\",       \"success\": \"성공여부\",       \"data\": {         JSON 데이터       }     }     ```
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppleSignInRequestDto
 */
export interface AppleSignInRequestDto {
    /**
     * 애플 로그인 시 받는 유저 이름
     * @type {string}
     * @memberof AppleSignInRequestDto
     */
    fullName: string;
    /**
     * 애플 로그인 시 발급받은 id token
     * @type {string}
     * @memberof AppleSignInRequestDto
     */
    idToken: string;
}

export function AppleSignInRequestDtoFromJSON(json: any): AppleSignInRequestDto {
    return AppleSignInRequestDtoFromJSONTyped(json, false);
}

export function AppleSignInRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppleSignInRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'idToken': json['idToken'],
    };
}

export function AppleSignInRequestDtoToJSON(value?: AppleSignInRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'idToken': value.idToken,
    };
}


