/* tslint:disable */
/* eslint-disable */
/**
 * 냥팔자 API 명세
 * 냥파자는 상팔자 어플리케이션을 위한 API 명세서입니다. - 모든 API의 Path는 **\'/api\'로 시작**합니다. - 모든 API의 응답은 **공통 응답 형식**을 가집니다. data에 실제 응답 데이터가 들어갑니다.     ```json     {       \"requestId\": \"서버생성 요청ID\",       \"requestTime\": \"요청시간\",       \"success\": \"성공여부\",       \"data\": {         JSON 데이터       }     }     ```
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DivinationQuestionSolveCheckResponseDto
 */
export interface DivinationQuestionSolveCheckResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof DivinationQuestionSolveCheckResponseDto
     */
    isSolved: boolean;
    /**
     * 
     * @type {number}
     * @memberof DivinationQuestionSolveCheckResponseDto
     */
    resultId?: number;
}

export function DivinationQuestionSolveCheckResponseDtoFromJSON(json: any): DivinationQuestionSolveCheckResponseDto {
    return DivinationQuestionSolveCheckResponseDtoFromJSONTyped(json, false);
}

export function DivinationQuestionSolveCheckResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DivinationQuestionSolveCheckResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isSolved': json['isSolved'],
        'resultId': !exists(json, 'resultId') ? undefined : json['resultId'],
    };
}

export function DivinationQuestionSolveCheckResponseDtoToJSON(value?: DivinationQuestionSolveCheckResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isSolved': value.isSolved,
        'resultId': value.resultId,
    };
}


