/* tslint:disable */
/* eslint-disable */
/**
 * 냥팔자 API 명세
 * 냥파자는 상팔자 어플리케이션을 위한 API 명세서입니다. - 모든 API의 Path는 **\'/api\'로 시작**합니다. - 모든 API의 응답은 **공통 응답 형식**을 가집니다. data에 실제 응답 데이터가 들어갑니다.     ```json     {       \"requestId\": \"서버생성 요청ID\",       \"requestTime\": \"요청시간\",       \"success\": \"성공여부\",       \"data\": {         JSON 데이터       }     }     ```
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 시간 (HH:mm)
 * @export
 * @interface LocalTime
 */
export interface LocalTime {
    /**
     * 
     * @type {number}
     * @memberof LocalTime
     */
    hour?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalTime
     */
    minute?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalTime
     */
    nano?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalTime
     */
    second?: number;
}

export function LocalTimeFromJSON(json: any): LocalTime {
    return LocalTimeFromJSONTyped(json, false);
}

export function LocalTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hour': !exists(json, 'hour') ? undefined : json['hour'],
        'minute': !exists(json, 'minute') ? undefined : json['minute'],
        'nano': !exists(json, 'nano') ? undefined : json['nano'],
        'second': !exists(json, 'second') ? undefined : json['second'],
    };
}

export function LocalTimeToJSON(value?: LocalTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hour': value.hour,
        'minute': value.minute,
        'nano': value.nano,
        'second': value.second,
    };
}


