/* tslint:disable */
/* eslint-disable */
/**
 * DDD API 명세
 * DDD(개발 한 스푼) 어플리케이션을 위한 API 명세서입니다. - 모든 API의 Path는 **\'/api\'로 시작**합니다. - 모든 API의 응답은 **공통 응답 형식**을 가집니다. data에 실제 응답 데이터가 들어갑니다.     ```json     {       \"requestId\": \"서버생성 요청ID\",       \"requestTime\": \"요청시간\",       \"success\": \"성공여부\",       \"data\": {         JSON 데이터       }     }     ```
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TokenResponseDto
 */
export interface TokenResponseDto {
  /**
   * 타로냥 접근용 jwt Token
   * @type {string}
   * @memberof TokenResponseDto
   */
  accessToken: string;
}

export function TokenResponseDtoFromJSON(json: any): TokenResponseDto {
  return TokenResponseDtoFromJSONTyped(json, false);
}

export function TokenResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TokenResponseDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accessToken: json['accessToken'],
  };
}

export function TokenResponseDtoToJSON(value?: TokenResponseDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    accessToken: value.accessToken,
  };
}
