/* tslint:disable */
/* eslint-disable */
/**
 * 냥팔자 API 명세
 * 냥파자는 상팔자 어플리케이션을 위한 API 명세서입니다. - 모든 API의 Path는 **\'/api\'로 시작**합니다. - 모든 API의 응답은 **공통 응답 형식**을 가집니다. data에 실제 응답 데이터가 들어갑니다.     ```json     {       \"requestId\": \"서버생성 요청ID\",       \"requestTime\": \"요청시간\",       \"success\": \"성공여부\",       \"data\": {         JSON 데이터       }     }     ```
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalTime,
    LocalTimeFromJSON,
    LocalTimeFromJSONTyped,
    LocalTimeToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserProfileResponseDto
 */
export interface UserProfileResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponseDto
     */
    birthType?: UserProfileResponseDtoBirthTypeEnum;
    /**
     * 날짜 (ISO 8601, yyyy-MM-dd)
     * @type {Date}
     * @memberof UserProfileResponseDto
     */
    birthday?: Date;
    /**
     * 
     * @type {LocalTime}
     * @memberof UserProfileResponseDto
     */
    birthtime?: LocalTime;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponseDto
     */
    gender?: UserProfileResponseDtoGenderEnum;
}

export function UserProfileResponseDtoFromJSON(json: any): UserProfileResponseDto {
    return UserProfileResponseDtoFromJSONTyped(json, false);
}

export function UserProfileResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'birthType': !exists(json, 'birthType') ? undefined : json['birthType'],
        'birthday': !exists(json, 'birthday') ? undefined : (new Date(json['birthday'])),
        'birthtime': !exists(json, 'birthtime') ? undefined : LocalTimeFromJSON(json['birthtime']),
        'email': !exists(json, 'email') ? undefined : json['email'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
    };
}

export function UserProfileResponseDtoToJSON(value?: UserProfileResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'birthType': value.birthType,
        'birthday': value.birthday === undefined ? undefined : (value.birthday.toISOString().substr(0,10)),
        'birthtime': LocalTimeToJSON(value.birthtime),
        'email': value.email,
        'gender': value.gender,
    };
}

/**
* @export
* @enum {string}
*/
export enum UserProfileResponseDtoBirthTypeEnum {
    SOLAR = 'SOLAR',
    LUNAR = 'LUNAR',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum UserProfileResponseDtoGenderEnum {
    MALE = 'MALE',
    FEMALE = 'FEMALE'
}


